depth: 24
pos_drop: 0.0
head_drop: 0.1
embed: conv
indim: 1024
InputShape: [32,32]
outdim: 1024
middim: [32,32,32,32]
rank: 256
activation: GELU
attn_drop: 0.0
proj_drop: 0.0
heads: 16
mlp1_outdim: 4096
mlp1_middim: [32,32,64,64]
mlp2_InputShape: [64,64]
mlp2_middim: [64,64,32,32]
mlp1_rank: False
mlp2_rank: False
mlp1_dropout: 0.1
mlp2_dropout: 0.1
qkv_bias: True
mlp1_bias: True
mlp2_bias: True
qk_norm: False
latent_attn: False
onlyattn: False

InterRes_Pos:
  q: False
  k: False
  v: False
  out: False
  mlp1: False
  mlp2: False

IntraRes_Pos:
  q: False
  k: False
  v: False
  out: False
  mlp1: False
  mlp2: False

InterResGate_Pos:
  q: False
  k: False
  v: False
  out: False
  mlp1: False
  mlp2: False

TenserizedGate_Pos:
  q: False
  k: False
  v: False
  out: False
  mlp1: False
  mlp2: False

IntraResGate_Pos:
  q: False
  k: False
  v: False
  out: False
  mlp1: False
  mlp2: False

LatentAct_Pos:
  q: False
  k: False
  v: False
  out: False
  mlp1: False
  mlp2: False

bn_Pos:
  q: False
  k: False
  v: False
  out: False
  mlp1: False
  mlp2: False

fact_Pos:
  q: False
  k: False
  v: False
  out: False
  mlp1: False
  mlp2: False

